export interface DocsTocItem {
  readonly label: string;
  readonly fragment: string;
}

export interface DocsNavItem {
  readonly label: string;
  readonly path?: string;
  readonly toc?: readonly DocsTocItem[];
}

export interface DocsNavGroup {
  readonly label: string;
  readonly items: readonly DocsNavItem[];
}

export const docsNavGroups: readonly DocsNavGroup[] = [
  {
    label: 'Getting Started',
    items: [
      { label: 'Introduction', path: '/docs/introduction' },
      { label: 'Installation', path: '/docs/installation' },
      { label: 'Inspired Designs', path: '/docs/inspired-designs' },
      {
        label: 'FAQ',
        path: '/docs/faq',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'What it is', fragment: 'what-is-neo-brutalism' },
          { label: 'Why React', fragment: 'why-react' },
          { label: 'Modern React', fragment: 'modern-react' },
          { label: 'Tailwind v4', fragment: 'tailwind-v4' },
          { label: 'Comparison', fragment: 'library-comparison' },
          { label: 'Production readiness', fragment: 'production-readiness' },
          { label: 'Components', fragment: 'components-included' },
          { label: 'SSR', fragment: 'ssr' },
          { label: 'Author', fragment: 'who-made-it' },
        ],
      },
    ],
  },
  {
    label: 'Composition',
    items: [
      {
        label: 'Overview',
        path: '/composition/overview',
        toc: [
          { label: 'Mental model', fragment: 'mental-model' },
          { label: 'Decision guide', fragment: 'decision-guide' },
          { label: 'Rendered example', fragment: 'example' },
          { label: 'Before / after', fragment: 'before-after' },
          { label: 'API language', fragment: 'api-language' },
          { label: 'Customization', fragment: 'customization' },
        ],
      },
      {
        label: 'Surface & Section',
        path: '/composition/surface-and-section',
        toc: [
          { label: 'How they relate', fragment: 'relationship' },
          { label: 'Basic panel', fragment: 'basic-panel' },
          { label: 'Header / body / footer', fragment: 'header-body-footer' },
          { label: 'The clip input', fragment: 'clip' },
          { label: 'When to use', fragment: 'when-to-use' },
          { label: 'Key inputs', fragment: 'api' },
        ],
      },
      {
        label: 'Stack & Cluster',
        path: '/composition/stack-and-cluster',
        toc: [
          { label: 'When to use each', fragment: 'when-each' },
          { label: 'Stack example', fragment: 'stack-example' },
          { label: 'Cluster example', fragment: 'cluster-example' },
          { label: 'Combined', fragment: 'combined-example' },
          { label: 'Gap values', fragment: 'gap-values' },
          { label: 'Key inputs', fragment: 'api' },
        ],
      },
      {
        label: 'Split Layouts',
        path: '/composition/split-layouts',
        toc: [
          { label: 'How it works', fragment: 'how-it-works' },
          { label: 'Hero split', fragment: 'hero-split' },
          { label: 'Media / content', fragment: 'media-content' },
          { label: 'Key inputs', fragment: 'api' },
          { label: 'When to use', fragment: 'when-to-use' },
        ],
      },
      {
        label: 'Common Patterns',
        path: '/composition/common-patterns',
        toc: [
          { label: 'Card shell', fragment: 'card-shell' },
          { label: 'Toolbar row', fragment: 'toolbar-row' },
          { label: 'Feature stack', fragment: 'feature-stack' },
          { label: 'Callout panel', fragment: 'callout-panel' },
          { label: 'Two-column card', fragment: 'two-column-card' },
          { label: 'Primitives used panel', fragment: 'primitives-used-panel' },
        ],
      },
    ],
  },
  {
    label: 'Recipes',
    items: [
      {
        label: 'Travel Card',
        path: '/recipes/travel-card',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Code', fragment: 'code' },
          { label: 'Primitives used', fragment: 'primitives' },
          { label: 'Layout breakdown', fragment: 'layout-breakdown' },
        ],
      },
      {
        label: 'Open to Work Card',
        path: '/recipes/open-to-work-card',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Code', fragment: 'code' },
          { label: 'Primitives used', fragment: 'primitives' },
          { label: 'Layout breakdown', fragment: 'layout-breakdown' },
        ],
      },
      {
        label: 'Podcast Card',
        path: '/recipes/podcast-card',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Code', fragment: 'code' },
          { label: 'Primitives used', fragment: 'primitives' },
          { label: 'Layout breakdown', fragment: 'layout-breakdown' },
        ],
      },
    ],
  },
  {
    label: 'Primitives',
    items: [
      { label: 'Alert', path: '/components/alert' },
      { label: 'Alert Dialog', path: '/components/alert-dialog' },
      {
        label: 'Accordion',
        path: '/components/accordion',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Single collapsible', fragment: 'single-collapsible' },
          { label: 'Multiple', fragment: 'multiple' },
          { label: 'Disabled item', fragment: 'disabled-item' },
          { label: 'Default opened item', fragment: 'default-open' },
          { label: 'API', fragment: 'api' },
        ],
      },
      { label: 'Avatar', path: '/components/avatar' },
      {
        label: 'Avatar Group',
        path: '/components/avatar-group',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Without overflow', fragment: 'no-overflow' },
          { label: 'API', fragment: 'api' },
        ],
      },
      { label: 'Badge', path: '/components/badge' },
      { label: 'Breadcrumb', path: '/components/breadcrumb' },
      {
        label: 'Button',
        path: '/components/button',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Tones', fragment: 'tones' },
          { label: 'Sizes', fragment: 'sizes' },
          { label: 'CTA', fragment: 'cta' },
          { label: 'Trailing Icon', fragment: 'trailing-icon' },
          { label: 'Full width', fragment: 'full-width' },
          { label: 'Disabled', fragment: 'disabled' },
          { label: 'Anchor usage', fragment: 'anchor-usage' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Callout',
        path: '/components/callout',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Examples', fragment: 'examples' },
          { label: 'Tones', fragment: 'tones' },
          { label: 'Sizes', fragment: 'sizes' },
          { label: 'Layouts', fragment: 'layouts' },
          { label: 'Shadows', fragment: 'shadows' },
          { label: 'Customization', fragment: 'customization' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Calendar',
        path: '/components/calendar',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Range', fragment: 'range' },
          { label: 'Disabled', fragment: 'disabled' },
          { label: 'API', fragment: 'api' },
        ],
      },
      { label: 'Card', path: '/components/card' },
      {
        label: 'Carousel',
        path: '/components/carousel',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Loop & autoplay', fragment: 'loop' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Chart',
        path: '/components/chart',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Dependencies', fragment: 'dependencies' },
          { label: 'Bar', fragment: 'bar' },
          { label: 'Line', fragment: 'line' },
          { label: 'Area', fragment: 'area' },
          { label: 'Pie', fragment: 'pie' },
          { label: 'Tooltips', fragment: 'tooltips' },
          { label: 'Theme', fragment: 'theme' },
          { label: 'API', fragment: 'api' },
        ],
      },
      { label: 'Checkbox', path: '/components/checkbox' },
      { label: 'Collapsible', path: '/components/collapsible' },
      {
        label: 'Combobox',
        path: '/components/combobox',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'When to Use', fragment: 'when-to-use' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'With Label', fragment: 'with-label' },
          { label: 'Controlled', fragment: 'controlled' },
          { label: 'Clearable', fragment: 'clearable' },
          { label: 'Empty State', fragment: 'empty-state' },
          { label: 'Input Group', fragment: 'input-group' },
          { label: 'With Icons', fragment: 'with-icons' },
          { label: 'Disabled', fragment: 'disabled' },
          { label: 'Custom Background', fragment: 'custom-background' },
          { label: 'Customization', fragment: 'customization' },
          { label: 'Accessibility', fragment: 'accessibility' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Command',
        path: '/components/command',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'When to Use', fragment: 'when-to-use' },
          { label: 'Dependencies', fragment: 'dependencies' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Command Dialog', fragment: 'dialog' },
          { label: 'Groups & Shortcuts', fragment: 'groups-shortcuts' },
          { label: 'Empty State', fragment: 'empty-state' },
          { label: 'Disabled Item', fragment: 'disabled-item' },
          { label: 'Async Search', fragment: 'async-search' },
          { label: 'Custom Background', fragment: 'custom-background' },
          { label: 'Customization', fragment: 'customization' },
          { label: 'Accessibility', fragment: 'accessibility' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Context Menu',
        path: '/components/context-menu',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'When to Use', fragment: 'when-to-use' },
          { label: 'Dependencies', fragment: 'dependencies' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'With Icons', fragment: 'with-icons' },
          { label: 'Groups', fragment: 'groups' },
          { label: 'Submenu', fragment: 'submenu' },
          { label: 'Controlled', fragment: 'controlled' },
          { label: 'Checkbox Items', fragment: 'checkbox' },
          { label: 'Radio Group', fragment: 'radio' },
          { label: 'Custom Background', fragment: 'custom-background' },
          { label: 'Customization', fragment: 'customization' },
          { label: 'Accessibility', fragment: 'accessibility' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Chip',
        path: '/components/chip',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Tones', fragment: 'tones' },
          { label: 'With Icon', fragment: 'with-icon' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Cluster',
        path: '/components/cluster',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Gaps', fragment: 'gaps' },
          { label: 'Alignment', fragment: 'alignment' },
          { label: 'Justification', fragment: 'justification' },
          { label: 'Wrapping', fragment: 'wrapping' },
          { label: 'Separators', fragment: 'separators' },
          { label: 'Composition', fragment: 'composition' },
          { label: 'Responsive gap', fragment: 'responsive' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Data Table',
        path: '/components/data-table',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'When to Use', fragment: 'when-to-use' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Controlled', fragment: 'controlled' },
          { label: 'Server-side Mode', fragment: 'server-side' },
          { label: 'Custom Toolbar', fragment: 'toolbar' },
          { label: 'Sticky Header', fragment: 'sticky-header' },
          { label: 'Row Click', fragment: 'row-click' },
          { label: 'Row Selection', fragment: 'selection' },
          { label: 'Loading', fragment: 'loading' },
          { label: 'Headless Hook', fragment: 'headless' },
          { label: 'Customization', fragment: 'customization' },
          { label: 'Accessibility', fragment: 'accessibility' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Date Picker',
        path: '/components/date-picker',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'When to Use', fragment: 'when-to-use' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Range', fragment: 'range' },
          { label: 'Input Variant', fragment: 'input-variant' },
          { label: 'Controlled', fragment: 'controlled' },
          { label: 'Clearable', fragment: 'clearable' },
          { label: 'Disabled', fragment: 'disabled' },
          { label: 'Presets', fragment: 'presets' },
          { label: 'Disabled Dates', fragment: 'disabled-dates' },
          { label: 'With Label', fragment: 'with-label' },
          { label: 'Input Group', fragment: 'input-group' },
          { label: 'Custom Background', fragment: 'custom-background' },
          { label: 'Customization', fragment: 'customization' },
          { label: 'Accessibility', fragment: 'accessibility' },
          { label: 'API', fragment: 'api' },
        ],
      },
      { label: 'Dialog', path: '/components/dialog' },
      { label: 'Drawer', path: '/components/drawer' },
      { label: 'Dropdown Menu', path: '/components/dropdown-menu' },
      {
        label: 'Display',
        path: '/components/display',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Sizes', fragment: 'sizes' },
          { label: 'Color', fragment: 'color' },
          { label: 'Custom Size', fragment: 'custom-size' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Halftone',
        path: '/components/halftone',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Positions', fragment: 'positions' },
          { label: 'Custom Color', fragment: 'custom-color' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Icon',
        path: '/components/icon',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Sizes', fragment: 'sizes' },
          { label: 'Tones', fragment: 'tones' },
          { label: 'Modes', fragment: 'modes' },
          { label: 'Accessibility', fragment: 'accessibility' },
          { label: 'Composition', fragment: 'composition' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Icon Button',
        path: '/components/icon-button',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Shapes', fragment: 'shapes' },
          { label: 'Sizes', fragment: 'sizes' },
          { label: 'Tones', fragment: 'tones' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Form',
        path: '/components/form',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'When to Use', fragment: 'when-to-use' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Schema Validation', fragment: 'validation' },
          { label: 'Composite Controls', fragment: 'composite-controls' },
          { label: 'Submitting State', fragment: 'submitting' },
          { label: 'Horizontal Fields', fragment: 'horizontal' },
          { label: 'Manual Provider', fragment: 'provider' },
          { label: 'Customization', fragment: 'customization' },
          { label: 'Accessibility', fragment: 'accessibility' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Hover Card',
        path: '/components/hover-card',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'When to Use', fragment: 'when-to-use' },
          { label: 'Dependencies', fragment: 'dependencies' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Accessibility', fragment: 'accessibility' },
          { label: 'API', fragment: 'api' },
        ],
      },
      { label: 'Image Card', path: '/components/image-card' },
      { label: 'Input OTP', path: '/components/input-otp' },
      {
        label: 'Input',
        path: '/components/input',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Sizes', fragment: 'sizes' },
          { label: 'Disabled', fragment: 'disabled' },
          { label: 'With Label', fragment: 'with-label' },
          { label: 'With Button', fragment: 'with-button' },
          { label: 'File', fragment: 'file' },
          { label: 'Customization', fragment: 'customization' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Input Group',
        path: '/components/input-group',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Prefix and Suffix', fragment: 'prefix-suffix' },
          { label: 'With Label', fragment: 'with-label' },
          { label: 'Textarea', fragment: 'textarea' },
          { label: 'Disabled', fragment: 'disabled' },
          { label: 'API', fragment: 'api' },
        ],
      },
      { label: 'Label', path: '/components/label' },
      { label: 'Marquee', path: '/components/marquee' },
      {
        label: 'Menubar',
        path: '/components/menubar',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'When to Use', fragment: 'when-to-use' },
          { label: 'Dependencies', fragment: 'dependencies' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Submenu', fragment: 'submenu' },
          { label: 'Accessibility', fragment: 'accessibility' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Navigation Menu',
        path: '/components/navigation-menu',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'When to Use', fragment: 'when-to-use' },
          { label: 'Dependencies', fragment: 'dependencies' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Viewport', fragment: 'viewport' },
          { label: 'Accessibility', fragment: 'accessibility' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Media Frame',
        path: '/components/media-frame',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Examples', fragment: 'examples' },
          { label: 'Tones', fragment: 'tones' },
          { label: 'Ratios', fragment: 'ratios' },
          { label: 'Fit', fragment: 'fit' },
          { label: 'Shape', fragment: 'shape' },
          { label: 'Customization', fragment: 'customization' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Media Item',
        path: '/components/media-item',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Variants', fragment: 'variants' },
          { label: 'Orientations', fragment: 'orientations' },
          { label: 'With description', fragment: 'with-description' },
          { label: 'Sizes', fragment: 'sizes' },
          { label: 'Tones', fragment: 'tones' },
          { label: 'Alignment', fragment: 'alignment' },
          { label: 'Real-world examples', fragment: 'real-world' },
          { label: 'API', fragment: 'api' },
        ],
      },
      { label: 'Pagination', path: '/components/pagination' },
      { label: 'Popover', path: '/components/popover' },
      {
        label: 'Progress',
        path: '/components/progress',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Tones', fragment: 'tones' },
          { label: 'API', fragment: 'api' },
        ],
      },
      { label: 'Radio Group', path: '/components/radio-group' },
      {
        label: 'Rating',
        path: '/components/rating',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Values', fragment: 'values' },
          { label: 'With count', fragment: 'with-count' },
          { label: 'Custom max', fragment: 'custom-max' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Section',
        path: '/components/section',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Paddings', fragment: 'paddings' },
          { label: 'Borders', fragment: 'borders' },
          { label: 'Border styles', fragment: 'border-styles' },
          { label: 'Layouts', fragment: 'layouts' },
          { label: 'Composition', fragment: 'composition' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Resizable',
        path: '/components/resizable',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'When to Use', fragment: 'when-to-use' },
          { label: 'Dependencies', fragment: 'dependencies' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Accessibility', fragment: 'accessibility' },
          { label: 'API', fragment: 'api' },
        ],
      },
      { label: 'Scroll Area', path: '/components/scroll-area' },
      {
        label: 'Select',
        path: '/components/select',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'With Label', fragment: 'with-label' },
          { label: 'Input Group', fragment: 'input-group' },
          { label: 'Disabled', fragment: 'disabled' },
          { label: 'Custom Background', fragment: 'custom-background' },
          { label: 'API', fragment: 'api' },
        ],
      },
      { label: 'Sheet', path: '/components/sheet' },
      {
        label: 'Sidebar',
        path: '/components/sidebar',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'When to Use', fragment: 'when-to-use' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Collapse', fragment: 'collapse' },
          { label: 'Accessibility', fragment: 'accessibility' },
          { label: 'API', fragment: 'api' },
        ],
      },
      { label: 'Skeleton', path: '/components/skeleton' },
      { label: 'Slider', path: '/components/slider' },
      { label: 'Switch', path: '/components/switch' },
      {
        label: 'Separator',
        path: '/components/separator',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Variants', fragment: 'variants' },
          { label: 'Vertical', fragment: 'orientation' },
          { label: 'Custom Color', fragment: 'custom-color' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Split',
        path: '/components/split',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Ratios', fragment: 'ratios' },
          { label: 'Gaps and padding', fragment: 'gaps-padding' },
          { label: 'Collapse', fragment: 'collapse' },
          { label: 'Alignment', fragment: 'alignment' },
          { label: 'Separators', fragment: 'separators' },
          { label: 'Composition', fragment: 'composition' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Stack',
        path: '/components/stack',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Gaps', fragment: 'gaps' },
          { label: 'Alignment', fragment: 'alignment' },
          { label: 'Justification', fragment: 'justification' },
          { label: 'Separators', fragment: 'separators' },
          { label: 'Responsive gap', fragment: 'responsive' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Stat',
        path: '/components/stat',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'With icon', fragment: 'with-icon' },
          { label: 'Row direction', fragment: 'row-direction' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Status Dot',
        path: '/components/status-dot',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'States', fragment: 'states' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Sticker',
        path: '/components/sticker',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Shapes', fragment: 'shapes' },
          { label: 'Tones', fragment: 'tones' },
          { label: 'Rotation', fragment: 'rotate' },
          { label: 'API', fragment: 'api' },
        ],
      },
      { label: 'Table', path: '/components/table' },
      { label: 'Tabs', path: '/components/tabs' },
      { label: 'Toast', path: '/components/toast' },
      { label: 'Tooltip', path: '/components/tooltip' },
      {
        label: 'Surface',
        path: '/components/surface',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Tones', fragment: 'tones' },
          { label: 'Shape', fragment: 'shape' },
          { label: 'Clip', fragment: 'clip' },
          { label: 'Customization', fragment: 'customization' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Text',
        path: '/components/text',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Sizes', fragment: 'sizes' },
          { label: 'Weights', fragment: 'weights' },
          { label: 'Tones', fragment: 'tones' },
          { label: 'Transform', fragment: 'transform' },
          { label: 'Tracking', fragment: 'tracking' },
          { label: 'Measure', fragment: 'measure' },
          { label: 'Leading', fragment: 'leading' },
          { label: 'Composition', fragment: 'composition' },
          { label: 'API', fragment: 'api' },
        ],
      },
      { label: 'Textarea', path: '/components/textarea' },
      {
        label: 'Title',
        path: '/components/title',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Custom Wave', fragment: 'custom-wave' },
          { label: 'Mixed Content', fragment: 'mixed-content' },
          { label: 'Customization', fragment: 'customization' },
          { label: 'API', fragment: 'api' },
        ],
      },
      {
        label: 'Typography',
        path: '/components/typography',
        toc: [
          { label: 'Overview', fragment: 'overview' },
          { label: 'Preview', fragment: 'preview' },
          { label: 'Usage', fragment: 'usage' },
          { label: 'Font tokens', fragment: 'fonts' },
          { label: 'Composition', fragment: 'composition' },
          { label: 'API', fragment: 'api' },
        ],
      },
    ],
  },
];

export const docsNavItems: readonly DocsNavItem[] = docsNavGroups.flatMap(
  (group) => group.items
);

export function findDocsNavItem(path: string): DocsNavItem | undefined {
  const normalizedPath = path.split(/[?#]/, 1)[0] || '/';

  return docsNavItems.find((item) => item.path === normalizedPath);
}
